const EMPLOYEE_LABEL = {
	employee_id: "Employee ID",
	employee_number: "Employee Number",
	dependent_number: "Dependent Number",
	role: "Role",
	first_name: "First Name",
	middle_name: "Middle Name",
	last_name: "Last Name",
	SSN: "SSN",
	date_of_birth: "Date of Birth",
	email: "Email",
	user_name: "User Name",
	password: "Password",
	group_number: "Group Number",
	location_name: "Location Name",
	gender: "Gender",
	dependent_type: "Dependent Type",
	marital_status: "Marital Status",
	relationship: "Relationship",
	upload_type: "Upload Type",
	address_line_1: "Address Line 1",
	address_line_2: "Address Line 2",
	city: "City",
	state: "State",
	country: "Country",
	ZIP: "ZIP Code",
	contact_label: "Contact Label",
	phone_number: "Phone Number",
	phone_extension: "Phone Extension",
	hire_date: "Hire Date",
	employment_status: "Employment Status",
	dependent_profile_access: "Dependent Profile Access",
	employee_profile_access: "Employee Profile Access",
	is_registered: "Is Registered",
	event_date: "Event Date",
	event_name: "Event Name",
	event_document: "Event Document",
	created_by: "Created By",
	last_login_date: "Last Login Date"
};

export default EMPLOYEE_LABEL;
