import { Member } from "../../@types/member.types";

const employee: Member = {
	_id: "61a97f71a2153b40b8135a41",
	member_id: "ARI1",
	first_name: "Steven",
	middle_name: "Debjit",
	last_name: "George",
	user_name: "Steven",
	password: "$2a$10$avuYW4fqyWCNzMM0ncwN1.fLh44Pc6udt79rJ4IVdnPOA7FF5hvZa",
	upload_type: "MANUAL",
	address_line_1: "72 Morningside DR",
	address_line_2: "Subway",
	city: "Austin",
	state: "Texas(TX)",
	country: "USA - United States of America",
	ZIP: "798979813",
	phone_number: 9330724843,
	phone_extension: 11,
	group_number: 184,
	hire_date: "1640131200000",
	employee_status: "ACTIVE",
	dependent_profile_access: false,
	is_registered: true,
	last_login_date: "1648765791876",
	SSN: "148975483",
	date_of_birth: "1988-08-01T00:00:00.000Z",
	gender: "FEMALE",
	marital_status: "SINGLE",
	email: "digelecx@gmail.com",
	contact_label: "BUSINESS",
	employee_number: 38,
	dependent_type: null,
	event_date: "null",
	event_document: null,
	event_name: null,
	relationship: null,
	dependent_wlt_id: null,
	role: "EMPLOYEE",
	dependent_number: 0,
	employee_wlt_id: null,
	location_number: 23,
	employee_SSN: "",
	hire_location_number: null,
	dependent_benefit_term_reason: null,
	dependent_status: null,
	is_active: false,
	is_term: false,
	term_date: "",
	term_reason: null,
	date: "",
	location: {
		location_name: "Brookshire Brother 23 - Dallas"
	},
	group: {
		name: "Brookshire Brothers"
	}
};

const dependents: Member[] = [
	{
		_id: "61a97f71a2153b40b8135a42",
		member_id: "ARI1",
		first_name: "Wendy",
		middle_name: "Debjit",
		last_name: "George",
		user_name: "Wendy",
		password: "$2a$10$avuYW4fqyWCNzMM0ncwN1.fLh44Pc6udt79rJ4IVdnPOA7FF5hvZa",
		upload_type: "MANUAL",
		address_line_1: "72 Morningside DR",
		address_line_2: "Subway",
		city: "Austin",
		state: "Texas(TX)",
		country: "USA - United States of America",
		ZIP: "798979813",
		phone_number: 9330724843,
		phone_extension: 11,
		group_number: 184,
		hire_date: "1640131200000",
		employee_status: "ACTIVE",
		dependent_profile_access: false,
		is_registered: true,
		last_login_date: "1648765791876",
		SSN: "148975486",
		date_of_birth: "1988-08-01T00:00:00.000Z",
		gender: "FEMALE",
		marital_status: "SINGLE",
		email: "digelecx@gmail.com",
		contact_label: "BUSINESS",
		employee_number: 38,
		dependent_type: null,
		event_date: "null",
		event_document: null,
		event_name: null,
		relationship: "SPOUSE",
		dependent_wlt_id: null,
		role: "DEPENDENT",
		dependent_number: 0,
		employee_wlt_id: null,
		location_number: 23,
		employee_SSN: "148975483",
		hire_location_number: null,
		dependent_benefit_term_reason: null,
		dependent_status: null,
		is_active: false,
		is_term: false,
		term_date: "",
		term_reason: null,
		date: "",
		location: {
			location_name: "Brookshire Brother 23 - Dallas"
		},
		group: {
			name: "Brookshire Brothers"
		}
	},
	{
		_id: "61a97f71a2153b40b8135a42",
		member_id: "ARI1",
		first_name: "Emily",
		middle_name: "Debjit",
		last_name: "George",
		user_name: "Emily",
		password: "$2a$10$avuYW4fqyWCNzMM0ncwN1.fLh44Pc6udt79rJ4IVdnPOA7FF5hvZa",
		upload_type: "MANUAL",
		address_line_1: "72 Morningside DR",
		address_line_2: "Subway",
		city: "Austin",
		state: "Texas(TX)",
		country: "USA - United States of America",
		ZIP: "798979813",
		phone_number: 9330724843,
		phone_extension: 11,
		group_number: 184,
		hire_date: "1640131200000",
		employee_status: "ACTIVE",
		dependent_profile_access: false,
		is_registered: true,
		last_login_date: "1648765791876",
		SSN: "148975485",
		date_of_birth: "1988-08-01T00:00:00.000Z",
		gender: "FEMALE",
		marital_status: "SINGLE",
		email: "digelecx@gmail.com",
		contact_label: "BUSINESS",
		employee_number: 38,
		dependent_type: null,
		event_date: "null",
		event_document: null,
		event_name: null,
		relationship: "STEPCHILD",
		dependent_wlt_id: null,
		role: "DEPENDENT",
		dependent_number: 0,
		employee_wlt_id: null,
		location_number: 23,
		employee_SSN: "148975483",
		hire_location_number: null,
		dependent_benefit_term_reason: null,
		dependent_status: null,
		is_active: false,
		is_term: false,
		term_date: "",
		term_reason: null,
		date: "",
		location: {
			location_name: "Brookshire Brother 23 - Dallas"
		},
		group: {
			name: "Brookshire Brothers"
		}
	},
	{
		_id: "61a97f71a2153b40b8135a42",
		member_id: "ARI1",
		first_name: "Jonjoe",
		middle_name: "Debjit",
		last_name: "Kenny",
		user_name: "Wendy",
		password: "$2a$10$avuYW4fqyWCNzMM0ncwN1.fLh44Pc6udt79rJ4IVdnPOA7FF5hvZa",
		upload_type: "MANUAL",
		address_line_1: "72 Morningside DR",
		address_line_2: "Subway",
		city: "Austin",
		state: "Texas(TX)",
		country: "USA - United States of America",
		ZIP: "798979813",
		phone_number: 9330724843,
		phone_extension: 11,
		group_number: 184,
		hire_date: "1640131200000",
		employee_status: "ACTIVE",
		dependent_profile_access: false,
		is_registered: true,
		last_login_date: "1648765791876",
		SSN: "148975484",
		date_of_birth: "1988-08-01T00:00:00.000Z",
		gender: "FEMALE",
		marital_status: "SINGLE",
		email: "digelecx@gmail.com",
		contact_label: "BUSINESS",
		employee_number: 38,
		dependent_type: null,
		event_date: "null",
		event_document: null,
		event_name: null,
		relationship: "GODSON",
		dependent_wlt_id: null,
		role: "DEPENDENT",
		dependent_number: 0,
		employee_wlt_id: null,
		location_number: 23,
		employee_SSN: "148975483",
		hire_location_number: null,
		dependent_benefit_term_reason: null,
		dependent_status: null,
		is_active: false,
		is_term: false,
		term_date: "",
		term_reason: null,
		date: "",
		location: {
			location_name: "Brookshire Brother 23 - Dallas"
		},
		group: {
			name: "Brookshire Brothers"
		}
	}
];

export const EMPLOYEE = employee;
export const DEPENDENTS = dependents;
