const adminDashboardHeader = {
	user_status: "User Status",
	employees: "Employees",
	document_administration: "Document Administration",
	upload_administration: "Upload Administration",
	my_profile: "My Profile",
	limit_groups: "Limit Groups",
	limit_locations: "Limit Locations",
	user_information: "User Information",
	health_links: "Health Links",
	edit_health_links: "Edit Health Links",
	health_links_group_assign: "Health Links Group Assign",
	announcements: "Announcements",
	edit_announcements: "Edit Announcement",
	group_assign: "Announcement Group Assign",
	announcement_limit_groups: "Announcement Limit Groups",
	location_assign: "Announcement Location Assign",
	employee_page_design: "Employee Page Design",
	notifications: "Notifications",
	create_user: "Create User",
	create_employee: "Create Employee",
	add_dependent: "Add Dependent",
	approve_dependent: "Approve Dependent",
	search_member: "Search Member",
	members: "Members",
	employee_mapping: "Employee Mapping",
	lincoln_enrollment_form: "Lincoln Enrollment Form",
	static_plan_creation: "Static Plan Creation",
	email_notification_managements: "Email Notifications Management",
	dashBoard: "Dashboard",
	add_location: "Add Location",
	all_locations: "All Locations",
	all_members: "All Members",
	plan_management: "Plan Management",
	edit_location: "Edit Location",
	group_home: "Group Home"
};

export const ADMIN_DASHBOARD_HEADER = adminDashboardHeader;
